Nixos: try to fix test flakyness

diff --git a/nix/pkgs/rm-emu/bin/run_vm b/nix/pkgs/rm-emu/bin/run_vm
--- a/nix/pkgs/rm-emu/bin/run_vm
+++ b/nix/pkgs/rm-emu/bin/run_vm
@@ -18,7 +18,9 @@ if ! [ -f "$root_path" ] && [ -f "$backing_path" ]; then
     echo "No image found, creating new one at $root_path"
     qemu-img create -b "$backing_path" -F qcow2 -f qcow2 "$root_path"
   fi
-  chattr +C "$root_path"
+
+  # || true so extr4 fs don't fail.
+  chattr +C "$root_path" || true
 fi
 
 load_state=""
